# Generated by Django 5.0.2 on 2024-03-05 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='rage/')),
                ('name', models.CharField(max_length=560)),
                ('job', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name': 'rage',
                'verbose_name_plural': 'rage_team',
            },
        ),
    ]
