# Generated by Django 5.0.2 on 2024-02-28 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Studies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('link', models.URLField()),
            ],
            options={
                'verbose_name': 'study_video',
                'verbose_name_plural': 'study_videos',
            },
        ),
    ]
