# Generated by Django 5.0.2 on 2024-03-15 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abouts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='is_activae',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
    ]
