# Generated by Django 5.0.2 on 2024-03-12 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='artist',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
    ]
