# Generated by Django 5.0.2 on 2024-03-15 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0002_track_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='music',
            field=models.FileField(default=1, upload_to='musics', verbose_name='Музыка'),
            preserve_default=False,
        ),
    ]
