# Generated by Django 5.0.2 on 2024-03-15 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0003_track_music'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='rating',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
