# Generated by Django 5.0.2 on 2024-03-18 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0004_track_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='rating',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
